// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VedurConsole;

namespace VedurConsole.Migrations
{
    [DbContext(typeof(WeatherContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("VedurConsole.Models.Weather", b =>
                {
                    b.Property<long>("WeatherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("Breidd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Daggarmark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Haed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Hiti")
                        .HasColumnType("float");

                    b.Property<string>("Lengd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Loftthrystingur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nafn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nr")
                        .HasColumnType("int");

                    b.Property<string>("Nr_Vedurstofa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PntX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PntY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Raki")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sjavarhaed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vindatt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VindattAsc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VindattStDev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vindhradi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vindhvida")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WeatherID");

                    b.ToTable("Weather");
                });
#pragma warning restore 612, 618
        }
    }
}
